### ISSUE TITLE
gen_stdb.py polarity and azcorr problem

### ISSUE THREAD

**Issue by graczer** [schaefferaj/StDb#14]
Maybe raising an issue isn't the best way to ask about it, but in the line
https://github.com/schaefferaj/StDb/blob/404ec0a6a84656adc196b3b873973700a2cb1de6/Scripts/gen_stdb.py#L178
instead of "polarity=1." shouldn't  be "polarity=pol" ?
And in the next line:
"azcorr=0" => "azcorr=azcor"

With the current version of the software the azimuthal correction will be always 0 in the database.

**Comment by paudetseis** [comment]
Thank you for raising these points. We have updated the master branch. You can now fetch and merge the updated master.
