### ISSUE TITLE
Fix location codes

### ISSUE THREAD

**Issue by paudetseis** [schaefferaj/StDb#17]
This issue was raised in `SplitPy`: https://github.com/paudetseis/SplitPy/issues/8 and concerns the handling of location codes in the script `query_fdsn_stdb.py`.

The issue was partially fixed by adding an argument `-L` to specify the location code of interest. For example, `query_fdsn_stdb.py -N IU -S ANMO -L 00 db`. The code currently only handles one location code as argument (no comma-separated values). See commit https://github.com/schaefferaj/StDb/commit/f7d880d11cd7ff93992ec5fc2d8002ef88ccefb5 

In (partially) fixing this issue, a new one came up where the default `chnrank` option gets superseded by the sorting done in the `inventory` object. So even though the `chnrank` has first item `'LH'` by default, the first channel available in the inventory object is `'BH'`. 

To do:
- [ ] Fix code to use a list of location codes (will have to fix the station keys in that case to use a long form) as input
- [ ] Fix the sorting of channels in inventory to use 'chnrank`

**Comment by paudetseis** [comment]
@schaefferaj does the new commit https://github.com/schaefferaj/StDb/commit/8183b1716b11933c6b37cf2d89120b5874228849 resolve the issue above? If so, we can probably close it

**Comment by schaefferaj** [comment]
@paudetseis, yes, this new commit (8183b17) does resolve the issue above. Multiple location codes can be specified, the channel follows channel rank, and a db entry is only returned if the location code(s) exist for the specified channel. Also, the start/end dates return correspond specifically to the channel code, not the station start/end dates as was used previously.
